apiVersion: v1
kind: Pod
metadata:
  name: yogs
  labels:
    name: yogs
spec:
  containers:
  - name: yogs
    image: gcr.io/kuar-demo/kuard-amd64:1
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 1
      failureThreshold: 3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
