apiVersion: v1
kind: Pod
metadata:
  name: yogs
  labels:
    name: yogs
spec:
  volumes:
    - name: "yogs-data"
      hostPath:
        path: "/var/liv/yogs"
  containers:
  - name: yogs
    image: gcr.io/kuar-demo/kuard-amd64:1
    volumeMounts:
      - mountPath: "/data"
        name: "yogs-data"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        name: http 
        protocol: TCP
