apiVersion: v1
kind: Pod
metadata:
  name: pod-resource
  labels:
    name: pod-resource
spec:
  containers:
  - name: pod-resource
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
